[versions]
agp = "9.1.1"
commons-io = "2.22.0"
jnigen-commons = "3.1.2"
ktlint = "1.8.0"
semver4j = "6.0.0"
shadow = "9.6.1"
spotless = "8.10.2"

[libraries]
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
jnigen-commons = { module = "com.badlogicgames.jnigen:jnigen-commons", version.ref = "jnigen-commons" }
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
semver4j = { module = "org.semver4j:semver4j", version.ref = "semver4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
